x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: docker/Dockerfile.airflow

  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
    AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    PROJECT_DIR: /opt/workspace
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_CONF_DIR: /opt/hive/conf
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/workspace/data
    - ./spark_jobs:/opt/workspace/spark_jobs
    - ./retail_etl:/opt/workspace/retail_etl
    - ./hive/conf:/opt/hive/conf
    - spark-warehouse:/opt/hive/data/warehouse
    - airflow-logs:/opt/airflow/logs

  depends_on:
    airflow-postgres:
      condition: service_healthy

services:

  airflow-postgres:
    image: postgres:15
    container_name: airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - airflow-postgres-db:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    user: "0:0"

    entrypoint: /bin/bash

    command:
      - -c
      - >
        mkdir -p /opt/airflow/logs/scheduler /opt/airflow/logs/dag_processor_manager &&
        mkdir -p /opt/hive/data/warehouse &&
        chown -R 50000:0 /opt/hive/data/warehouse &&
        chown -R 50000:0 /opt/airflow/logs &&
        airflow db migrate &&
        airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com || true

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver

    command: webserver

    ports:
      - "8081:8080"

    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/health')\""]
      interval: 15s
      timeout: 10s
      retries: 5

    depends_on:
      airflow-init:
        condition: service_completed_successfully

      airflow-postgres:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler

    command: scheduler

    depends_on:
      airflow-init:
        condition: service_completed_successfully

      airflow-postgres:
        condition: service_healthy

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"

    ports:
      - "8080:8080"
      - "7077:7077"

    environment:
      SPARK_CONF_DIR: /opt/hive/conf

    volumes:
      - ./data:/opt/workspace/data
      - ./spark_jobs:/opt/workspace/spark_jobs
      - ./retail_etl:/opt/workspace/retail_etl
      - ./hive/conf:/opt/hive/conf
      - spark-warehouse:/opt/hive/data/warehouse

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    hostname: spark-worker
    user: "0:0"

    depends_on:
      - spark-master

    environment:
      SPARK_CONF_DIR: /opt/hive/conf

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --webui-port
      - "8081"
      - --cores
      - "2"
      - --memory
      - 2g

    volumes:
      - ./data:/opt/workspace/data
      - ./spark_jobs:/opt/workspace/spark_jobs
      - ./retail_etl:/opt/workspace/retail_etl
      - ./hive/conf:/opt/hive/conf
      - spark-warehouse:/opt/hive/data/warehouse

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore

    environment:
      SERVICE_NAME: metastore
      HIVE_CUSTOM_CONF_DIR: /opt/hive/conf

    ports:
      - "9083:9083"

    volumes:
      - ./hive/conf:/opt/hive/conf
      - spark-warehouse:/opt/hive/data/warehouse

volumes:
  airflow-postgres-db:
  spark-warehouse:
  airflow-logs:
