services:

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master

    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077

      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    hostname: spark-worker

    depends_on:
      - spark-master

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    command: >
      start-notebook.py
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_remote_access=True

    ports:
      - "8888:8888"

    volumes:
      - ../:/home/jovyan/work
      